-- Source: demo_data/postgres_investments_embeddings2.sql
-- Type: SQL_STATEMENT
-- Chunk: 7
----------------------------------------
/* Raw instrument reference as JSON */ CREATE TABLE raw_reference.instrument_ref_json (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, as_of_date DATE, payload JSONB /* contains ISIN, ticker, asset_class, region, etc. */)