-- Source: demo_data/postgres_investments_embeddings2.sql
-- Type: SQL_STATEMENT
-- Chunk: 13
----------------------------------------
/* Structured instrument dimension staging from JSON */ CREATE TABLE stg_investments.instrument_dim (instrument_key INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, isin TEXT UNIQUE, ticker TEXT, asset_class TEXT, region TEXT, sector TEXT, currency TEXT, as_of_date DATE)