-- Source: demo_data/postgres_investments_embeddings2.sql
-- Type: SQL_STATEMENT
-- Chunk: 15
----------------------------------------
/* Intraday position staging table */ CREATE TABLE stg_investments.position_intraday (position_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, trade_ts TIMESTAMPTZ, trade_date DATE, account_code TEXT, instrument_isin TEXT, quantity DECIMAL(20, 4), price_ccy DECIMAL(18, 6), currency TEXT, source_system TEXT)