-- Source: demo_data/postgres_investments_embeddings.sql
-- Type: SQL_STATEMENT
-- Chunk: 5
----------------------------------------
CREATE TABLE raw_market.trade_feed_venue_b (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, exec_time TIMESTAMPTZ, portfolio TEXT, ticker TEXT, direction TEXT /* 'B'/'S' */, qty DECIMAL(20, 4), gross_amount DECIMAL(18, 6) /* quantity * price */, ccy TEXT, source_system TEXT DEFAULT 'VENUE_B')