-- Source: demo_data/postgres_investments_embeddings.sql
-- Type: SQL_STATEMENT
-- Chunk: 4
----------------------------------------
/* ========================= */ /* 2. Raw landing tables */ /* ========================= */ /* Raw trade feeds (heterogeneous) */ CREATE TABLE raw_market.trade_feed_venue_a (trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, venue_trade_id TEXT, trade_ts TIMESTAMPTZ, account_code TEXT, isin TEXT, side TEXT /* 'BUY'/'SELL' */, quantity DECIMAL(20, 4), price DECIMAL(18, 6), currency TEXT /* e.g. 'USD','EUR' */, source_system TEXT DEFAULT 'VENUE_A')