-- Source: demo_data/postgres_investments_embeddings.sql
-- Type: SQL_STATEMENT
-- Chunk: 19
----------------------------------------
/* ========================= */ /* 4. Triggered audit with additional transformations */ /* ========================= */ CREATE TABLE stg_investments.position_intraday_audit (audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, position_id BIGINT, trade_ts TIMESTAMPTZ, account_code TEXT, instrument_isin TEXT, quantity DECIMAL(20, 4), price_ccy DECIMAL(18, 6), notional_ccy DECIMAL(30, 10), notional_usd DECIMAL(30, 10), currency TEXT, audit_ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)